// <auto-generated />
using System;
using System.Collections.Generic;
using Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("BrandId");

                    b.PrimitiveCollection<List<Guid>>("CategoryIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("CategoryIds");

                    b.PrimitiveCollection<List<string>>("Colors")
                        .HasColumnType("jsonb")
                        .HasColumnName("Colors");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOnUtc");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("Featured");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTimeOffset>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedOnUtc");

                    b.Property<string>("LongDescription")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("LongDescription");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("Published");

                    b.Property<string>("SEODescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("SEODescription");

                    b.Property<string>("SEOTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("SEOTitle");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SalePrice");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ShortDescription");

                    b.PrimitiveCollection<List<string>>("Sizes")
                        .HasColumnType("jsonb")
                        .HasColumnName("Sizes");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Sku");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("Tags");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Unit");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Weight");

                    b.HasKey("Id");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("IX_Products_BrandId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("Published")
                        .HasDatabaseName("IX_Products_Published");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Sku");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Products_Status");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.ProductImageEntity", b =>
                {
                    b.Property<string>("FileId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("FileId");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FileName");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("OriginalFileName");

                    b.Property<string>("PublicURL")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("PublicURL");

                    b.HasKey("FileId");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductImages_FileId");

                    b.ToTable("ProductImages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
